audio:
  chunk_size: 264600
  dim_f: 1024
  dim_t: 256
  hop_length: 441
  n_fft: 2048
  num_channels: 2
  sample_rate: 44100
  min_mean_abs: 000

model:
  dim: 384
  depth: 6
  stereo: true
  num_stems: 1
  time_transformer_depth: 1
  freq_transformer_depth: 1
  num_bands: 60
  dim_head: 64
  heads: 8
  attn_dropout: 0
  ff_dropout: 0
  flash_attn: True
  dim_freqs_in: 1025
  sample_rate: 44100  # needed for mel filter bank from librosa
  stft_n_fft: 2048
  stft_hop_length: 441
  stft_win_length: 2048
  stft_normalized: False
  mask_estimator_depth: 2
  multi_stft_resolution_loss_weight: 1.0
  multi_stft_resolutions_window_sizes: !!python/tuple
  - 4096
  - 2048
  - 1024
  - 512
  - 256
  multi_stft_hop_size: 147
  multi_stft_normalized: False
  mlp_expansion_factor: 1 # Probably too big (requires a lot of memory for weights)
  use_torch_checkpoint: False  # it allows to greatly reduce GPU memory consumption during training (not fully tested)
  skip_connection: True # Enable skip connection between transformer blocks - can solve problem with gradients and probably faster training
  
training:
  batch_size: 15
  gradient_accumulation_steps: 1
  grad_clip: 0
  instruments:
  - Similarity
  - Difference
  lr: 1.0
  patience: 5
  reduce_factor: 0.95
  target_instrument: Similarity
  num_epochs: 1000
  num_steps: 1057
  q: 0.95
  coarse_loss_clip: true
  ema_momentum: 0.999
  optimizer: prodigy
  other_fix: false # it's needed for checking on multisong dataset if other is actually instrumental
  use_amp: true # enable or disable usage of mixed precision (float16) - usually it must be true

augmentations:
  enable: true # enable or disable all augmentations (to fast disable if needed)
  loudness: true # randomly change loudness of each stem on the range (loudness_min; loudness_max)
  loudness_min: 0.5
  loudness_max: 1.5
  all:
    channel_shuffle: 0.5 # Set 0 or lower to disable
    random_inverse: 0.05 # inverse track (better lower probability)
    random_polarity: 0.5 # polarity change (multiply waveform to -1)

    # pedalboard pitch shift block
    pedalboard_pitch_shift: 0.01
    pedalboard_pitch_shift_semitones_min: -7
    pedalboard_pitch_shift_semitones_max: 7

    # pedalboard resample block
    pedalboard_resample: 0.001
    pedalboard_resample_target_sample_rate_min: 4000
    pedalboard_resample_target_sample_rate_max: 44100

    mp3_compression: 0.01
    mp3_compression_min_bitrate: 32
    mp3_compression_max_bitrate: 320
    mp3_compression_backend: "lameenc"

inference:
  batch_size: 2
  dim_t: 256
  num_overlap: 1

lora:
  r: 8
  lora_alpha: 16. #alpha / rank > 1
  lora_dropout: 0.05
  merge_weights: True
  fan_in_fan_out: False